#ROCKHOPPER_ROOT = /usr/src/cvswork/ROCKHOPPER
ARCHITECTURE 	?= v4t_le
BUILD_ROOT      = $(ROCKHOPPER_ROOT)/build
SOURCE_ROOT     = $(ROCKHOPPER_ROOT)/source
TOOLS_ROOT      = $(ROCKHOPPER_ROOT)/tools
TARGET_ROOT     = $(ROCKHOPPER_ROOT)/target
IMAGES_ROOT     = $(ROCKHOPPER_ROOT)/images
KERNEL_BUILD	= $(BUILD_ROOT)/kernel/linux/work/linux

RH_CFLAGS	= -DROCKHOPPER=1 \
		-DLCHKEY_HANDLE_BY_APP \
		-g \
		-DRH_DEBUG=1 \
		-mshort-load-bytes \
		-mtune=arm9tdmi \
		-msoft-float

ROCKHOPPER      =1
export RH_CFLAGS ROCKHOPPER

CFLAGSPLUS = -DTIWLN_WINCE30 \
	-DTIWLN_MAJOR_VERSION=4 \
	-DTIWLN_MINOR_VERSION=0 \
	-DINCLUDE_FRAGMENTATION \
	-DINCLUDE_DEFRAGMENTATION \
	-DCONFIGURE_BSS_TYPE_STA \
	-DTI_DBG_LOG \
	-DTIACXWLN_EXPORTS \
	-DTI_DBG \
	-DINON_DBG \
	-D__BYTE_ORDER_LITTLE_ENDIAN \
	-DCONFIGURE_BSS_TYPE_STA \
	-DMODVERSIONS \
	-include $(WLND_ROOT)/pform/linux/inc/linux/modversions.h \
	-DNOT_SUPPORT_32_BIT_ACCESS_COMMAND \
	-DIPMT_PACK \
	-O2

#CFLAGSPLUS += -DIPMT_DEBUG_IPMT_INIT_ERROR
#CFLAGSPLUS += -DIPMT_DEBUG_OS_RECV_ERROR

#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_HANDLEINTERRUPTS	# PRINT  Handle SCAN_COMPLETE interrupt
#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_MEMCOPYTO	# PRINT  Timeout waiting Auto Increment register
#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_HWMBOXSENDCMD	# PRINT  error waiting for previous command complete
#CFLAGSPLUS += -DIPMT_NOTICE_TEST

#	-DIPMT_DEBUG_CONN \
#	-DIPMT_DEBUG_CONNIBSS \
#	-DIPMT_DEBUG_CONNINFRA \
#	-DIPMT_DEBUG_CONNSELF \
#	-DIPMT_DEBUG_SELECT \
#	-DIPMT_DEBUG_SITEMGR \
#	-DIPMT_DEBUG_SMESM \
#	-DIPMT_DEBUG_HW_CTL \
#	-DIPMT_DEBUG \
#	-DREPORT_LOG \
#	-DIPMT_DEBUG_IPMT_INIT \
#	-DIPMT_DEBUG_IPMT_OPEN \
#	-DIPMT_DEBUG_IPMT_STOP \
#	-DIPMT_DEBUG_IPMT_CLEANUP \
#	-DIPMT_DEBUG_IPMT_INITPROC \
#	-DIPMT_DEBUG_ALLOC_IPMTDEV \
#	-DIPMT_DEBUG_OS_RES \
#	-DIPMT_DEBUG_RES_CLOSE_IMAGE_FILES \
#	-DIPMT_DEBUG_READ_FW \
#	-DIPMT_DEBUG_SET_MCAST_LIST \
#	-DIPMT_DEBUG_SHUTDOWN \
#	-DIPMT_DEBUG_CONFIGMGR_HWRESET \
#	-DIPMT_DEBUG_WHAL_HWCTRL_INITIATE \
#	-DIPMT_DEBUG_WHAL_HWCTRL_RESET \
#	-DIPMT_DEBUG_WHAL_CTRL_HWRESET \
#	-DIPMT_DEBUG_OS_RES_ERROR \

#CFLAGSPLUS += -DIPMT_DEBUG_IPMT_INIT_ERROR
#CFLAGSPLUS += -DIPMT_DEBUG_OS_RECV_ERROR

#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_HANDLEINTERRUPTS	# PRINT  Handle SCAN_COMPLETE interrupt
#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_MEMCOPYTO	# PRINT  Timeout waiting Auto Increment register
#CFLAGSPLUS += -DIPMT_DEBUG_HWCTRL_HWMBOXSENDCMD	# PRINT  error waiting for previous command complete
#CFLAGSPLUS += -DIPMT_NOTICE_TEST


#	-DIPMT_PERFORM_TEST
#	-DIPMT_PERFORM_TEST_INS
#	-DIPMT_PERFORM_TEST_OPEN
#	-DIPMT_PERFORM_TEST_STOP
#	-DIPMT_PERFORM_TEST_CLEANUP
#	-DIPMT_PERFORM_TEST_IOCTL
#	-DIPMT_PERFORM_TEST_SEND
#	-DIPMT_PERFORM_TEST_SEND_SINGLE_MULTI
#	-DIPMT_PERFORM_TEST_SEND_FRAGMENT
#	-DIPMT_PERFORM_TEST_RECV
#	-DIPMT_PERFORM_TEST_RECV_SINGLE_MULTI
#	-DIPMT_PERFORM_TEST_RECV_DEFRAGMENT
#	-DIPMT_PERFORM_TEST_INS_1
#	-DIPMT_PERFORM_TEST_INS_2
#	-DIPMT_PERFORM_TEST_INS_3
#	-DIPMT_MEMORY_TEST
#	-DIPMT_MEMORY_TEST_PRINTK
#	-DIPMT_STACK_TEST

RH_BIN_PATH	= $(TOOLS_ROOT)/$(ARCHITECTURE)/bin

CROSS_COMPILE   = $(RH_BIN_PATH)/
AS              = $(CROSS_COMPILE)as
LD              = $(CROSS_COMPILE)ld
CC              = $(CROSS_COMPILE)gcc
CPP             = $(CC) -E
AR              = $(CROSS_COMPILE)ar
NM              = $(CROSS_COMPILE)nm
STRIP           = $(CROSS_COMPILE)strip
OBJCOPY         = $(CROSS_COMPILE)objcopy
OBJDUMP         = $(CROSS_COMPILE)objdump

#-DREPORT_INIT -DREPORT_SM -DREPORT_FATAL_ERROR -DREPORT_ERROR

#-DIPMT_DEBUG_HW_CTL :hal/hw_ctrl
#-DIPMT_DEBUG_OS_API :osApi.c
#-DIPMT_DEBUG_OS_NDIS:osNdis.c
#-DIPMT_DEBUG_OS_RECV:osRecv.c
#-DIPMT_DEBUG_OS_RES :osRes.c
#-DIPMT_DEBUG_IPMT   :ipmt.c


