/*
 * hcm_eep.h
 *
 * Copyright(C) 2011 Panasonic Mobile Communications Co., Ltd.
 *
 */
#ifndef __hcm_eep_h__                            /* __hcm_eep_h__             */
#define __hcm_eep_h__                            /* __hcm_eep_h__             */

#define PSIZE               16

#define D_HCM_FROM_ID_MIN       0
#define D_HCM_FROM_ID_MAX       2999 

#define D_HCM_FROM_PAGE_MIN     0x0000
#define D_HCM_FROM_PAGE_MAX     0x0690
#define PMIN                D_HCM_FROM_PAGE_MIN
#define PMAX                D_HCM_FROM_PAGE_MAX

#define D_HCM_UNV_ADDR_END      (PMAX * PSIZE - 1)

/* begin of EEPROM map define */
#define D_HCM_ALARM_DEFINI                   200
#define D_HCM_ALARM_PRI                      201
#define D_HCM_ALARM_DATA                     202
#define D_HCM_POWOFF_CNT                     204
#define D_HCM_TSD_COUNT                      205
#define D_HCM_SYUNDAN1_RST_COUNT             206
#define D_HCM_RST_COUNT                      207
#define D_HCM_POWON_COUNT                    203
#define D_HCM_INTEGRITY_COUNT                208
#define D_HCM_E_FGIC_I2C_ERROR_COUNT         392
#define D_HCM_POWOFF_FACT                    225
#define D_HCM_POWOFF_TIMESTAMP1              226
#define D_HCM_POWOFF_TIMESTAMP2              227
#define D_HCM_POWOFF_TIMESTAMP3              228
#define D_HCM_POWOFF_TIMESTAMP4              229
#define D_HCM_POWOFF_TIMESTAMP5              230
#define D_HCM_POWOFF_TIMESTAMP6              231
#define D_HCM_POWOFF_TIMESTAMP7              232
#define D_HCM_POWOFF_TIMESTAMP8              233
#define D_HCM_POWOFF_TIMESTAMP9              234
#define D_HCM_POWOFF_TIMESTAMP10             235
#define D_HCM_POWOFF_TIMESTAMP11             236
#define D_HCM_POWOFF_TIMESTAMP12             237
#define D_HCM_POWOFF_TIMESTAMP13             238
#define D_HCM_POWOFF_TIMESTAMP14             239
#define D_HCM_POWOFF_TIMESTAMP15             240
#define D_HCM_POWOFF_TIMESTAMP16             241
#define D_HCM_TSD_TIMESTAMP1                 242
#define D_HCM_TSD_TIMESTAMP2                 243
#define D_HCM_TSD_TIMESTAMP3                 244
#define D_HCM_TSD_TIMESTAMP4                 245
#define D_HCM_TSD_TIMESTAMP5                 246
#define D_HCM_TSD_TIMESTAMP6                 247
#define D_HCM_TSD_TIMESTAMP7                 248
#define D_HCM_TSD_TIMESTAMP8                 249
#define D_HCM_TSD_TIMESTAMP9                 250
#define D_HCM_TSD_TIMESTAMP10                251
#define D_HCM_TSD_TIMESTAMP11                252
#define D_HCM_TSD_TIMESTAMP12                253
#define D_HCM_TSD_TIMESTAMP13                254
#define D_HCM_TSD_TIMESTAMP14                255
#define D_HCM_TSD_TIMESTAMP15                256
#define D_HCM_TSD_TIMESTAMP16                257
#define D_HCM_SYUNDAN_RST_RSTRD_VALUE        258
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP1   259
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP2   260
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP3   261
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP4   262
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP5   263
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP6   264
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP7   265
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP8   266
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP9   267
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP10  268
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP11  269
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP12  270
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP13  271
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP14  272
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP15  273
#define D_HCM_SYUNDAN_RST_RSTRD_TIMESTAMP16  274
#define D_HCM_RSTFACTG_VALUE                 275
#define D_HCM_RST_TIMESTAMP1                 276
#define D_HCM_RST_TIMESTAMP2                 277
#define D_HCM_RST_TIMESTAMP3                 278
#define D_HCM_RST_TIMESTAMP4                 279
#define D_HCM_RST_TIMESTAMP5                 280
#define D_HCM_RST_TIMESTAMP6                 281
#define D_HCM_RST_TIMESTAMP7                 282
#define D_HCM_RST_TIMESTAMP8                 283
#define D_HCM_RST_TIMESTAMP9                 284
#define D_HCM_RST_TIMESTAMP10                285
#define D_HCM_RST_TIMESTAMP11                286
#define D_HCM_RST_TIMESTAMP12                287
#define D_HCM_RST_TIMESTAMP13                288
#define D_HCM_RST_TIMESTAMP14                289
#define D_HCM_RST_TIMESTAMP15                290
#define D_HCM_RST_TIMESTAMP16                291
#define D_HCM_POWON_FACT1                    292
#define D_HCM_POWON_FACT2                    293
#define D_HCM_POWON_FACT3                    294
#define D_HCM_POWON_FACT4                    295
#define D_HCM_POWON_TIMESTAMP1               209
#define D_HCM_POWON_TIMESTAMP2               210
#define D_HCM_POWON_TIMESTAMP3               211
#define D_HCM_POWON_TIMESTAMP4               212
#define D_HCM_POWON_TIMESTAMP5               213
#define D_HCM_POWON_TIMESTAMP6               214
#define D_HCM_POWON_TIMESTAMP7               215
#define D_HCM_POWON_TIMESTAMP8               216
#define D_HCM_POWON_TIMESTAMP9               217
#define D_HCM_POWON_TIMESTAMP10              218
#define D_HCM_POWON_TIMESTAMP11              219
#define D_HCM_POWON_TIMESTAMP12              220
#define D_HCM_POWON_TIMESTAMP13              221
#define D_HCM_POWON_TIMESTAMP14              222
#define D_HCM_POWON_TIMESTAMP15              223
#define D_HCM_POWON_TIMESTAMP16              224
#define D_HCM_POWON_TIMESTAMP17              296
#define D_HCM_POWON_TIMESTAMP18              297
#define D_HCM_POWON_TIMESTAMP19              298
#define D_HCM_POWON_TIMESTAMP20              299
#define D_HCM_POWON_TIMESTAMP21              300
#define D_HCM_POWON_TIMESTAMP22              301
#define D_HCM_POWON_TIMESTAMP23              302
#define D_HCM_POWON_TIMESTAMP24              303
#define D_HCM_POWON_TIMESTAMP25              304
#define D_HCM_POWON_TIMESTAMP26              305
#define D_HCM_POWON_TIMESTAMP27              306
#define D_HCM_POWON_TIMESTAMP28              307
#define D_HCM_POWON_TIMESTAMP29              308
#define D_HCM_POWON_TIMESTAMP30              309
#define D_HCM_POWON_TIMESTAMP31              310
#define D_HCM_POWON_TIMESTAMP32              311
#define D_HCM_POWON_TIMESTAMP33              312
#define D_HCM_POWON_TIMESTAMP34              313
#define D_HCM_POWON_TIMESTAMP35              314
#define D_HCM_POWON_TIMESTAMP36              315
#define D_HCM_POWON_TIMESTAMP37              316
#define D_HCM_POWON_TIMESTAMP38              317
#define D_HCM_POWON_TIMESTAMP39              318
#define D_HCM_POWON_TIMESTAMP40              319
#define D_HCM_POWON_TIMESTAMP41              320
#define D_HCM_POWON_TIMESTAMP42              321
#define D_HCM_POWON_TIMESTAMP43              322
#define D_HCM_POWON_TIMESTAMP44              323
#define D_HCM_POWON_TIMESTAMP45              324
#define D_HCM_POWON_TIMESTAMP46              325
#define D_HCM_POWON_TIMESTAMP47              326
#define D_HCM_POWON_TIMESTAMP48              327
#define D_HCM_POWON_TIMESTAMP49              328
#define D_HCM_POWON_TIMESTAMP50              329
#define D_HCM_POWON_TIMESTAMP51              330
#define D_HCM_POWON_TIMESTAMP52              331
#define D_HCM_POWON_TIMESTAMP53              332
#define D_HCM_POWON_TIMESTAMP54              333
#define D_HCM_POWON_TIMESTAMP55              334
#define D_HCM_POWON_TIMESTAMP56              335
#define D_HCM_POWON_TIMESTAMP57              336
#define D_HCM_POWON_TIMESTAMP58              337
#define D_HCM_POWON_TIMESTAMP59              338
#define D_HCM_POWON_TIMESTAMP60              339
#define D_HCM_POWON_TIMESTAMP61              340
#define D_HCM_POWON_TIMESTAMP62              341
#define D_HCM_POWON_TIMESTAMP63              342
#define D_HCM_POWON_TIMESTAMP64              343
#define D_HCM_INTEGRITY_TIMESTAMP1           344
#define D_HCM_INTEGRITY_TIMESTAMP2           345
#define D_HCM_INTEGRITY_TIMESTAMP3           346
#define D_HCM_INTEGRITY_TIMESTAMP4           347
#define D_HCM_INTEGRITY_TIMESTAMP5           348
#define D_HCM_INTEGRITY_TIMESTAMP6           349
#define D_HCM_INTEGRITY_TIMESTAMP7           350
#define D_HCM_INTEGRITY_TIMESTAMP8           351
#define D_HCM_INTEGRITY_TIMESTAMP9           352
#define D_HCM_INTEGRITY_TIMESTAMP10          353
#define D_HCM_INTEGRITY_TIMESTAMP11          354
#define D_HCM_INTEGRITY_TIMESTAMP12          355
#define D_HCM_INTEGRITY_TIMESTAMP13          356
#define D_HCM_INTEGRITY_TIMESTAMP14          357
#define D_HCM_INTEGRITY_TIMESTAMP15          358
#define D_HCM_INTEGRITY_TIMESTAMP16          359
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP1    438
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP2    439
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP3    440
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP4    441
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP5    442
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP6    443
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP7    444
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP8    445
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP9    446
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP10   447
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP11   448
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP12   449
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP13   450
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP14   451
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP15   452
#define D_HCM_E_FGIC_I2C_ERROR_TIMESTAMP16   453
#define D_HCM_E_FGIC_I2C_ERROR_CODE1         454
#define D_HCM_E_FGIC_I2C_ERROR_CODE2         455
#define D_HCM_E_FGIC_I2C_ERROR_CODE3         456
#define D_HCM_E_FGIC_I2C_ERROR_CODE4         457
#define D_HCM_E_FGIC_I2C_ERROR_CODE5         458
#define D_HCM_E_FGIC_I2C_ERROR_CODE6         459
#define D_HCM_E_FGIC_I2C_ERROR_CODE7         460
#define D_HCM_E_FGIC_I2C_ERROR_CODE8         461
#define D_HCM_E_FGIC_I2C_ERROR_CODE9         462
#define D_HCM_E_FGIC_I2C_ERROR_CODE10        463
#define D_HCM_E_FGIC_I2C_ERROR_CODE11        464
#define D_HCM_E_FGIC_I2C_ERROR_CODE12        465
#define D_HCM_E_FGIC_I2C_ERROR_CODE13        466
#define D_HCM_E_FGIC_I2C_ERROR_CODE14        467
#define D_HCM_E_FGIC_I2C_ERROR_CODE15        468
#define D_HCM_E_FGIC_I2C_ERROR_CODE16        469
#define D_HCM_E_FGIC_I2C_ERROR_PATH1         470
#define D_HCM_E_FGIC_I2C_ERROR_PATH2         471
#define D_HCM_E_FGIC_I2C_ERROR_PATH3         472
#define D_HCM_E_FGIC_I2C_ERROR_PATH4         473
#define D_HCM_E_FGIC_I2C_ERROR_PATH5         474
#define D_HCM_E_FGIC_I2C_ERROR_PATH6         475
#define D_HCM_E_FGIC_I2C_ERROR_PATH7         476
#define D_HCM_E_FGIC_I2C_ERROR_PATH8         477
#define D_HCM_E_FGIC_I2C_ERROR_PATH9         478
#define D_HCM_E_FGIC_I2C_ERROR_PATH10        479
#define D_HCM_E_FGIC_I2C_ERROR_PATH11        480
#define D_HCM_E_FGIC_I2C_ERROR_PATH12        481
#define D_HCM_E_FGIC_I2C_ERROR_PATH13        482
#define D_HCM_E_FGIC_I2C_ERROR_PATH14        483
#define D_HCM_E_FGIC_I2C_ERROR_PATH15        484
#define D_HCM_E_FGIC_I2C_ERROR_PATH16        485
#define D_HCM_TLLC_DEVICE                    400
#define D_HCM_USB_DEVICE_DESCRIPTOR          401
#define D_HCM_FeliCa_FUNCTION_SET            402
#define D_HCM_FELICA_REMOTE_FUNCTION_SET     416
#define D_HCM_FELICA_ICLOCK_FUNCTION_SET     417
#define D_HCM_FELICA_MDMLOCK_FUNCTION_SET    421
#define D_HCM_RSTDISPFACT                    403
#define D_HCM_ALLRST_FLG                     413
#define D_HCM_AUTO_NORA                      404
#define D_HCM_ABORT_ALARM_FLAG               405
#define D_HCM_E_UKDUMP_FLAG                  418
#define D_HCM_E_COLOG_CTRL_FLAG              398
#define D_HCM_E_COLOG_WDT_COUNT              399
#define D_HCM_E_COLOG_SHUNDAN_COUNT          394
#define D_HCM_E_BELOG_CTRL_FLAG              395
#define D_HCM_TLLC_STRING1                   406
#define D_HCM_TLLC_STRING2                   407
#define D_HCM_E_MASS_INQ_VENDORID            408
#define D_HCM_E_MASS_INQ_PRODUCTID           409
#define D_HCM_E_PWR_ONOFF                    410
#define D_HCM_E_SOFT_REWRITE_STS             411
#define D_HCM_E_MLCD_SELECT                  412
#define D_HCM_E_FOTA_FAILREASON                4
#define D_HCM_E_FOTA_BATT_THRESH               6
#define D_HCM_E_FOTA_RETRY_COUNT               7
#define D_HCM_USB_TETHERING_DESCRIPTOR       414
#define D_HCM_USB_TETHERING_DESCRIPTOR_WITH_ADB  415
#define D_HCM_E_FOTA_ERRORVALUE              419
#define D_HCM_E_FOTA_RECOVERYKERNEL_INFO     420
#define D_HCM_E_AD_BRB_EN                   2400
#define D_HCM_E_COLOG_REFRESHMEMMORY_COUNT   396
#define D_HCM_E_COLOG_REFRESHMEMMORY_TIMESTAMP  397
#define D_HCM_E_SD_MFRINFO_HST_CNT           360
#define D_HCM_E_SD_INIT_ERR_HST_CNT          361
#define D_HCM_E_CAM_STATIC_ELE_RST_CNT       362
#define D_HCM_E_VP_OPP_BLOCK_DISABLE_CNT     363
#define D_HCM_ABOOT_FACTOR1                  364
#define D_HCM_ABOOT_FACTOR2                  365
#define D_HCM_ABOOT_FACTOR3                  366
#define D_HCM_ABOOT_FACTOR4                  367
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP1    368
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP2    369
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP3    370
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP4    371
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP5    372
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP6    373
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP7    374
#define D_HCM_E_SD_MFRINFO_HST_TIMESTAMP8    375
#define D_HCM_E_SD_MFRINFO_HST1              376
#define D_HCM_E_SD_MFRINFO_HST2              377
#define D_HCM_E_SD_MFRINFO_HST3              378
#define D_HCM_E_SD_MFRINFO_HST4              379
#define D_HCM_E_SD_MFRINFO_HST5              380
#define D_HCM_E_SD_MFRINFO_HST6              381
#define D_HCM_E_SD_MFRINFO_HST7              382
#define D_HCM_E_SD_MFRINFO_HST8              383
#define D_HCM_E_SD_INIT_ERR_FACTOR1          384
#define D_HCM_E_SD_INIT_ERR_FACTOR2          385
#define D_HCM_E_SD_INIT_ERR_FACTOR3          386
#define D_HCM_E_SD_INIT_ERR_FACTOR4          387
#define D_HCM_E_SD_INIT_ERR_FACTOR5          388
#define D_HCM_E_SD_INIT_ERR_FACTOR6          389
#define D_HCM_E_SD_INIT_ERR_FACTOR7          390
#define D_HCM_E_SD_INIT_ERR_FACTOR8          391
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP1   486
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP2   487
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP3   488
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP4   489
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP5   490
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP6   491
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP7   492
#define D_HCM_E_SD_INIT_ERR_HST_TIMESTAMP8   493
#define D_HCM_E_CAM_STATIC_ELE_RST_TIMESTAMP  494
#define D_HCM_E_CAM_STATIC_ELE_RST_FACTOR    495
#define D_HCM_ABOOT_TIMESTAMP1               496
#define D_HCM_ABOOT_TIMESTAMP2               497
#define D_HCM_ABOOT_TIMESTAMP3               498
#define D_HCM_ABOOT_TIMESTAMP4               499
#define D_HCM_ABOOT_TIMESTAMP5               500
#define D_HCM_ABOOT_TIMESTAMP6               501
#define D_HCM_ABOOT_TIMESTAMP7               502
#define D_HCM_ABOOT_TIMESTAMP8               503
#define D_HCM_ABOOT_TIMESTAMP9               504
#define D_HCM_ABOOT_TIMESTAMP10              505
#define D_HCM_ABOOT_TIMESTAMP11              506
#define D_HCM_ABOOT_TIMESTAMP12              507
#define D_HCM_ABOOT_TIMESTAMP13              508
#define D_HCM_ABOOT_TIMESTAMP14              509
#define D_HCM_ABOOT_TIMESTAMP15              510
#define D_HCM_ABOOT_TIMESTAMP16              511
#define D_HCM_E_VP_CHG_ERR_DISABLE_TIMESTAMP  512
#define D_HCM_E_VP_WLAN_ERR_DISABLE_TIMESTAMP  513
#define D_HCM_E_VP_AMRCHG_ERR_DISABLE_TIMESTAMP  514
#define D_HCM_E_VP_CAM_ERR_DISABLE_TIMESTAMP  515
#define D_HCM_E_VP_CHG_WLAN_ERR_DISABLE_TIMESTAMP  516
#define D_HCM_E_VP_CAM_WLAN_DISABLE_TIMESTAMP  517
#define D_HCM_E_VP_DTV_BL_ERR_DISABLE_TIMESTAMP  518
#define D_HCM_E_VP_CHG_CAMERA_DISABLE_TIMESTAMP  519
#define D_HCM_E_VP_CHG_DTV_DISABLE_TIMESTAMP  520
#define D_HCM_E_VP_CAMERA_CAMERA_DISABLE_TIMESTAMP  521
#define D_HCM_E_VP_OPP_BLOCK_DISABLE_TIMESTAMP  522
#define D_HCM_E_INITIALIZE_SPARE00           422
#define D_HCM_E_INITIALIZE_SPARE01           423
#define D_HCM_E_INITIALIZE_SPARE02           424
#define D_HCM_E_INITIALIZE_SPARE03           425
#define D_HCM_E_INITIALIZE_SPARE04           426
#define D_HCM_E_INITIALIZE_SPARE05           427
#define D_HCM_E_INITIALIZE_SPARE06           428
#define D_HCM_E_INITIALIZE_SPARE07           429
#define D_HCM_E_INITIALIZE_SPARE08           430
#define D_HCM_E_INITIALIZE_SPARE09           431
#define D_HCM_E_INITIALIZE_SPARE10           432
#define D_HCM_E_INITIALIZE_SPARE11           433
#define D_HCM_E_INITIALIZE_SPARE12           434
#define D_HCM_E_INITIALIZE_SPARE13           435
#define D_HCM_E_INITIALIZE_SPARE14           436
#define D_HCM_E_INITIALIZE_SPARE15           437
#define D_HCM_AD_STEPTONE_TIME               583
#define D_HCM_AD_SAFE_TIMER                  584
#define D_HCM_AD_STEPTONE_WAIT              2404
#define D_HCM_AD_STEPTONE_STEPWIDTH         2405
#define D_HCM_AD_STEPTONE_STEPINT           2406
#define D_HCM_AD_STEPTONE_STEPINT_01        2407
#define D_HCM_AD_STEPTONE_TIME_01           2408
#define D_HCM_AD_STEPTONE_STEPWIDTH_01      2409
#define D_HCM_AD_STEPTONE_TIME_EM            657
#define D_HCM_AD_EARSAFETY_VOL               658
#define D_HCM_AD_STEPTONE_STEPINT_02        2418
#define D_HCM_AD_STEPTONE_TIME_02           2419
#define D_HCM_AD_STEPTONE_STEPWIDTH_02      2420
#define D_HCM_AD_SAFE_TIMER_02              2421
#define D_HCM_E_RING_STEP_SPHP_0             585
#define D_HCM_E_RING_STEP_SPHP_1             586
#define D_HCM_E_RING_STEP_SPHP_2             587
#define D_HCM_E_RING_STEP_SPHP_3             588
#define D_HCM_E_RING_STEP_SPHP_4             589
#define D_HCM_E_RING_STEP_SPHP_5             590
#define D_HCM_E_RING_STEP_SPHP_6             591
#define D_HCM_E_RING_STEP_SPHP_7             592
#define D_HCM_E_RING_STEP_SP_0               593
#define D_HCM_E_RING_STEP_SP_1               594
#define D_HCM_E_RING_STEP_SP_2               595
#define D_HCM_E_RING_STEP_SP_3               596
#define D_HCM_E_RING_STEP_SP_4               597
#define D_HCM_E_RING_STEP_SP_5               598
#define D_HCM_E_RING_STEP_SP_6               599
#define D_HCM_E_RING_STEP_SP_7               600
#define D_HCM_E_RING_STEP_REC_0              601
#define D_HCM_E_RING_STEP_REC_1              602
#define D_HCM_E_RING_STEP_REC_2              603
#define D_HCM_E_RING_STEP_REC_3              604
#define D_HCM_E_RING_STEP_REC_4              605
#define D_HCM_E_RING_STEP_REC_5              606
#define D_HCM_E_RING_STEP_REC_6              607
#define D_HCM_E_RING_STEP_REC_7              608
#define D_HCM_E_MEDIA_STEP_SP_0              609
#define D_HCM_E_MEDIA_STEP_SP_1              610
#define D_HCM_E_MEDIA_STEP_SP_2              611
#define D_HCM_E_MEDIA_STEP_SP_3              612
#define D_HCM_E_MEDIA_STEP_SP_4              613
#define D_HCM_E_MEDIA_STEP_SP_5              614
#define D_HCM_E_MEDIA_STEP_SP_6              615
#define D_HCM_E_MEDIA_STEP_SP_7              616
#define D_HCM_E_MEDIA_STEP_SP_8              617
#define D_HCM_E_MEDIA_STEP_SP_9              618
#define D_HCM_E_MEDIA_STEP_SP_10             619
#define D_HCM_E_MEDIA_STEP_SP_11             620
#define D_HCM_E_MEDIA_STEP_SP_12             621
#define D_HCM_E_MEDIA_STEP_SP_13             622
#define D_HCM_E_MEDIA_STEP_SP_14             623
#define D_HCM_E_MEDIA_STEP_SP_15             624
#define D_HCM_E_MEDIA_STEP_HP_0              625
#define D_HCM_E_MEDIA_STEP_HP_1              626
#define D_HCM_E_MEDIA_STEP_HP_2              627
#define D_HCM_E_MEDIA_STEP_HP_3              628
#define D_HCM_E_MEDIA_STEP_HP_4              629
#define D_HCM_E_MEDIA_STEP_HP_5              630
#define D_HCM_E_MEDIA_STEP_HP_6              631
#define D_HCM_E_MEDIA_STEP_HP_7              632
#define D_HCM_E_MEDIA_STEP_HP_8              633
#define D_HCM_E_MEDIA_STEP_HP_9              634
#define D_HCM_E_MEDIA_STEP_HP_10             635
#define D_HCM_E_MEDIA_STEP_HP_11             636
#define D_HCM_E_MEDIA_STEP_HP_12             637
#define D_HCM_E_MEDIA_STEP_HP_13             638
#define D_HCM_E_MEDIA_STEP_HP_14             639
#define D_HCM_E_MEDIA_STEP_HP_15             640
#define D_HCM_E_MEDIA_STEP_REC_0             641
#define D_HCM_E_MEDIA_STEP_REC_1             642
#define D_HCM_E_MEDIA_STEP_REC_2             643
#define D_HCM_E_MEDIA_STEP_REC_3             644
#define D_HCM_E_MEDIA_STEP_REC_4             645
#define D_HCM_E_MEDIA_STEP_REC_5             646
#define D_HCM_E_MEDIA_STEP_REC_6             647
#define D_HCM_E_MEDIA_STEP_REC_7             648
#define D_HCM_E_MEDIA_STEP_REC_8             649
#define D_HCM_E_MEDIA_STEP_REC_9             650
#define D_HCM_E_MEDIA_STEP_REC_10            651
#define D_HCM_E_MEDIA_STEP_REC_11            652
#define D_HCM_E_MEDIA_STEP_REC_12            653
#define D_HCM_E_MEDIA_STEP_REC_13            654
#define D_HCM_E_MEDIA_STEP_REC_14            655
#define D_HCM_E_MEDIA_STEP_REC_15            656
#define D_HCM_CHARGE_FIN_COUNT              1004
#define D_HCM_CHARGE_FIN_1STTIME            1005
#define D_HCM_CHARGE_FIN_TIMESTAMP          1011
#define D_HCM_CHARGE_FIN_SOC                1012
#define D_HCM_CHARGE_FIN_FCC                1013
#define D_HCM_DAT_GANYUDATA_01              1219
#define D_HCM_E_SPIDER3_CURRENT_SET         1001
#define D_HCM_E_SPIDER3_ERR_CNT             1002
#define D_HCM_SPIDER3_ERR_TIMESTAMP         1222
#define D_HCM_E_SPIDER3_ERR_REG_VALUE       1003
#define D_HCM_FG_PARAM2                     2410
#define D_HCM_E_SDETERIO_FTEMP              2411
#define D_HCM_E_DEGRADA_CONST_CYCLE         2412
#define D_HCM_E_SDETERIO_FVOL               2413
#define D_HCM_E_DEGRADA_BL50                2414
#define D_HCM_E_DEGRADA_BL50_SAVE_TSTAMP    2415
#define D_HCM_E_H24_SAVE                    2416
#define D_HCM_E_H24_SAVE_TSTAMP             2417
#define D_HCM_E_H24_SAVE_SOC                2432
#define D_HCM_RESUME_VOLTAGE                2434
#define D_HCM_TERM_CURRENT                  2435
#define D_HCM_TEMP_CHECK_PERIOD             2438
#define D_HCM_MAX_BAT_CHG_CURRENT           2439
#define D_HCM_COOL_BAT_CHG_CURRENT          2440
#define D_HCM_WARM_BAT_CHG_CURRENT          2441
#define D_HCM_COOL_BAT_CHG_VOLTAGE          2442
#define D_HCM_WARM_BAT_CHG_VOLTAGE          2443
#define D_HCM_TOTAL_TIMER                   2446
#define D_HCM_COOL_TEMP_DELTA               2447
#define D_HCM_WARM_TEMP_DELTA               2448
#define D_HCM_WIRELESSCHARGE_FIN_COUNT      2176
#define D_HCM_WIRELESSCHARGE_FIN_1STTIME    2177
#define D_HCM_WIRELESSCHARGE_FIN_TIMESTAMP  2178
#define D_HCM_WIRELESSCHARGE_FIN_SOC        2179
#define D_HCM_WIRELESSCHARGE_FIN_FCC        2180
#define D_HCM_FG_CHARGE1                    1036
#define D_HCM_FG_PARAM1                     1039
#define D_HCM_E_NO_LVA_FLG                  1042
#define D_HCM_FG_OCV_OKNG                   1043
#define D_HCM_FG_OCV_TIMESTAMP              1044
#define D_HCM_FG_OCV_TEMP                   1045
#define D_HCM_FG_OCV_VOLT                   1046
#define D_HCM_FG_OCV_NAC                    1047
#define D_HCM_FG_OCV_FAC                    1048
#define D_HCM_FG_OCV_RM                     1049
#define D_HCM_FG_OCV_FCC                    1050
#define D_HCM_FG_OCV_SOC                    1051
#define D_HCM_FG_OCV_COUNT                  1052
#define D_HCM_FG_CONSUMPTION_TIMESTAMP      1053
#define D_HCM_FG_CONSUMPTION_COUNT          1054
#define D_HCM_E_VP_HEAT_SUPPRESS            1055
#define D_HCM_E_VP_PERIOD                   1056
#define D_HCM_E_VP_HEAT_SUPPRESS2           1058
#define D_HCM_E_VP_CHG_DISABLE_TEMP1        1069
#define D_HCM_E_VP_CHG_DISABLE_TEMP2        1070
#define D_HCM_E_VP_CHG_DISABLE_TEMP3        1071
#define D_HCM_E_VP_CHG_DISABLE_TIME1        1072
#define D_HCM_E_VP_CHG_DISABLE_TIME2        1073
#define D_HCM_E_VP_CHG_DISABLE_TIME3        1074
#define D_HCM_E_VP_CHG_ENABLE_TEMP1         1075
#define D_HCM_E_VP_CHG_ENABLE_TEMP2         1076
#define D_HCM_E_VP_CHG_ENABLE_TEMP3         1077
#define D_HCM_E_VP_CHG_ENABLE_TIME1         1078
#define D_HCM_E_VP_CHG_ENABLE_TIME2         1079
#define D_HCM_E_VP_CHG_ENABLE_TIME3         1080
#define D_HCM_E_VP_CHG_ENABLE_OFFHOOK_TIME  1081
#define D_HCM_E_VP_WLAN_DISABLE_TEMP1       1082
#define D_HCM_E_VP_WLAN_DISABLE_TEMP2       1083
#define D_HCM_E_VP_WLAN_DISABLE_TEMP3       1084
#define D_HCM_E_VP_WLAN_DISABLE_TIME1       1085
#define D_HCM_E_VP_WLAN_DISABLE_TIME2       1086
#define D_HCM_E_VP_WLAN_DISABLE_TIME3       1087
#define D_HCM_E_VP_WLAN_ENABLE_TEMP1        1088
#define D_HCM_E_VP_WLAN_ENABLE_TEMP2        1089
#define D_HCM_E_VP_WLAN_ENABLE_TEMP3        1090
#define D_HCM_E_VP_WLAN_ENABLE_TIME1        1091
#define D_HCM_E_VP_WLAN_ENABLE_TIME2        1092
#define D_HCM_E_VP_WLAN_ENABLE_TIME3        1093
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP1     1095
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP2     1096
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP3     1097
#define D_HCM_E_VP_AMRCHG_DISABLE_TIME1     1098
#define D_HCM_E_VP_AMRCHG_DISABLE_TIME2     1099
#define D_HCM_E_VP_AMRCHG_DISABLE_TIME3     1100
#define D_HCM_E_VP_AMRCHG_ENABLE_TEMP1      1101
#define D_HCM_E_VP_AMRCHG_ENABLE_TEMP2      1102
#define D_HCM_E_VP_AMRCHG_ENABLE_TEMP3      1103
#define D_HCM_E_VP_AMRCHG_ENABLE_TIME1      1104
#define D_HCM_E_VP_AMRCHG_ENABLE_TIME2      1105
#define D_HCM_E_VP_AMRCHG_ENABLE_TIME3      1106
#define D_HCM_E_VP_AMRCHG_ENABLE_OFFHOOK_TIME 1107
#define D_HCM_E_VP_CAM_DISABLE_TEMP1        1108
#define D_HCM_E_VP_CAM_DISABLE_TEMP2        1109
#define D_HCM_E_VP_CAM_DISABLE_TEMP3        1110
#define D_HCM_E_VP_CAM_DISABLE_TIME1        1111
#define D_HCM_E_VP_CAM_DISABLE_TIME2        1112
#define D_HCM_E_VP_CAM_DISABLE_TIME3        1113
#define D_HCM_E_VP_CAM_ENABLE_TEMP1         1114
#define D_HCM_E_VP_CAM_ENABLE_TEMP2         1115
#define D_HCM_E_VP_CAM_ENABLE_TEMP3         1116
#define D_HCM_E_VP_CAM_ENABLE_TIME1         1117
#define D_HCM_E_VP_CAM_ENABLE_TIME2         1118
#define D_HCM_E_VP_CAM_ENABLE_TIME3         1119
#define D_HCM_E_VP_CHG_DISABLE_TEMP4        1121
#define D_HCM_E_VP_CHG_DISABLE_TEMP5        1122
#define D_HCM_E_VP_CHG_DISABLE_TEMP6        1123
#define D_HCM_E_VP_CHG_DISABLE_TIME4        1124
#define D_HCM_E_VP_CHG_DISABLE_TIME5        1125
#define D_HCM_E_VP_CHG_DISABLE_TIME6        1126
#define D_HCM_E_VP_CHG_ENABLE_TEMP4         1127
#define D_HCM_E_VP_CHG_ENABLE_TEMP5         1128
#define D_HCM_E_VP_CHG_ENABLE_TEMP6         1129
#define D_HCM_E_VP_CHG_ENABLE_TIME4         1130
#define D_HCM_E_VP_CHG_ENABLE_TIME5         1131
#define D_HCM_E_VP_CHG_ENABLE_TIME6         1132
#define D_HCM_E_VP_CHG_ENABLE_OFFHOOK_TIME2 1133
#define D_HCM_E_VP_CAM_DISABLE_TEMP4        1134
#define D_HCM_E_VP_CAM_DISABLE_TEMP5        1135
#define D_HCM_E_VP_CAM_DISABLE_TEMP6        1136
#define D_HCM_E_VP_CAM_DISABLE_TIME4        1137
#define D_HCM_E_VP_CAM_DISABLE_TIME5        1138
#define D_HCM_E_VP_CAM_DISABLE_TIME6        1139
#define D_HCM_E_VP_CAM_ENABLE_TEMP4         1140
#define D_HCM_E_VP_CAM_ENABLE_TEMP5         1141
#define D_HCM_E_VP_CAM_ENABLE_TEMP6         1142
#define D_HCM_E_VP_CAM_ENABLE_TIME4         1143
#define D_HCM_E_VP_CAM_ENABLE_TIME5         1144
#define D_HCM_E_VP_CAM_ENABLE_TIME6         1145
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP1     1223
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP2     1224
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP3     1225
#define D_HCM_E_VP_DTV_BL_DISABLE_TIME1     1226
#define D_HCM_E_VP_DTV_BL_DISABLE_TIME2     1227
#define D_HCM_E_VP_DTV_BL_DISABLE_TIME3     1228
#define D_HCM_E_VP_DTV_BL_ENABLE_TEMP1      1229
#define D_HCM_E_VP_DTV_BL_ENABLE_TEMP2      1230
#define D_HCM_E_VP_DTV_BL_ENABLE_TEMP3      1231
#define D_HCM_E_VP_DTV_BL_ENABLE_TIME1      1232
#define D_HCM_E_VP_DTV_BL_ENABLE_TIME2      1233
#define D_HCM_E_VP_DTV_BL_ENABLE_TIME3      1234
#define D_HCM_E_VP_CHG_DISABLE_TEMP7        1235
#define D_HCM_E_VP_CHG_DISABLE_TEMP8        1236
#define D_HCM_E_VP_CHG_DISABLE_TEMP9        1237
#define D_HCM_E_VP_CHG_DISABLE_TIME7        1238
#define D_HCM_E_VP_CHG_DISABLE_TIME8        1239
#define D_HCM_E_VP_CHG_DISABLE_TIME9        1240
#define D_HCM_E_VP_CHG_ENABLE_TEMP7         1241
#define D_HCM_E_VP_CHG_ENABLE_TEMP8         1242
#define D_HCM_E_VP_CHG_ENABLE_TEMP9         1243
#define D_HCM_E_VP_CHG_ENABLE_TIME7         1244
#define D_HCM_E_VP_CHG_ENABLE_TIME8         1245
#define D_HCM_E_VP_CHG_ENABLE_TIME9         1246
#define D_HCM_E_VP_CHG_ENABLE_OFFHOOK_TIME3 1247
#define D_HCM_E_VP_CHG_DISABLE_CNT          1173
#define D_HCM_E_VP_CHG_DISABLE_TEMP_LOG_S1  1174
#define D_HCM_E_VP_CHG_DISABLE_TEMP_LOG_S2  1175
#define D_HCM_E_VP_CHG_DISABLE_TEMP_LOG_S3  1176
#define D_HCM_E_VP_CHG_DISABLE_TIMESTAMP    1177
#define D_HCM_E_VP_WLAN_DISABLE_CNT         1178
#define D_HCM_E_VP_WLAN_DISABLE_TEMP_LOG_S1 1179
#define D_HCM_E_VP_WLAN_DISABLE_TEMP_LOG_S2 1180
#define D_HCM_E_VP_WLAN_DISABLE_TEMP_LOG_S3 1181
#define D_HCM_E_VP_WLAN_DISABLE_TIMESTAMP   1182
#define D_HCM_E_VP_AMRCHG_DISABLE_CNT       1183
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP_LOG_S1 1184
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP_LOG_S2 1185
#define D_HCM_E_VP_AMRCHG_DISABLE_TEMP_LOG_S3 1186
#define D_HCM_E_VP_AMRCHG_DISABLE_TIMESTAMP 1187
#define D_HCM_E_VP_CAM_DISABLE_CNT          1188
#define D_HCM_E_VP_CAM_DISABLE_TEMP_LOG_S1  1189
#define D_HCM_E_VP_CAM_DISABLE_TEMP_LOG_S2  1190
#define D_HCM_E_VP_CAM_DISABLE_TEMP_LOG_S3  1191
#define D_HCM_E_VP_CAM_DISABLE_TIMESTAMP    1192
#define D_HCM_E_VP_CHG_DISABLE2_CNT         1193
#define D_HCM_E_VP_CHG_DISABLE2_TEMP_LOG_S1 1194
#define D_HCM_E_VP_CHG_DISABLE2_TEMP_LOG_S2 1195
#define D_HCM_E_VP_CHG_DISABLE2_TEMP_LOG_S3 1196
#define D_HCM_E_VP_CHG_DISABLE2_TIMESTAMP   1197
#define D_HCM_E_VP_CAM_DISABLE2_CNT         1198
#define D_HCM_E_VP_CAM_DISABLE2_TEMP_LOG_S1 1199
#define D_HCM_E_VP_CAM_DISABLE2_TEMP_LOG_S2 1200
#define D_HCM_E_VP_CAM_DISABLE2_TEMP_LOG_S3 1201
#define D_HCM_E_VP_CAM_DISABLE2_TIMESTAMP   1202
#define D_HCM_E_VP_DTV_BL_DISABLE_CNT       1248
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP_LOG_S1 1249
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP_LOG_S2 1250
#define D_HCM_E_VP_DTV_BL_DISABLE_TEMP_LOG_S3 1251
#define D_HCM_E_VP_DTV_BL_DISABLE_TIMESTAMP 1252
#define D_HCM_E_VP_CHG_DISABLE3_CNT         1253
#define D_HCM_E_VP_CHG_DISABLE3_TEMP_LOG_S1 1254
#define D_HCM_E_VP_CHG_DISABLE3_TEMP_LOG_S2 1255
#define D_HCM_E_VP_CHG_DISABLE3_TEMP_LOG_S3 1256
#define D_HCM_E_VP_CHG_DISABLE3_TIMESTAMP   1257
#define D_HCM_E_VP_OPP_BLOCK_ABS_TEMP       1203
#define D_HCM_E_VP_OPP_BLOCK_REL_TEMP       1204
#define D_HCM_E_VP_OPP_BLOCK_ABS_NUM        1205
#define D_HCM_E_VP_OPP_BLOCK_REL_NUM        1206
#define D_HCM_E_VP_OPP_BLOCK_TEMP_MEAS_FREQ 1207
#define D_HCM_E_VP_OPP_BLOCK_TYPE           1057
#define D_HCM_E_VP_OPP_BLOCK_CNT            1208
#define D_HCM_E_VP_OPP_BLOCK_CPU_LOG        1209
#define D_HCM_E_VP_OPP_BLOCK_TEMP_LOG_S3    1210
#define D_HCM_E_VP_OPP_BLOCK_TEMP_LOG_S4    1211
#define D_HCM_E_VP_OPP_BLOCK_TIMESTAMP      1212
#define D_HCM_E_EXT_MODE1                   1213
#define D_HCM_E_EXT_MODE2                   1214
#define D_HCM_E_USBID                       1215
#define D_HCM_E_USB45TRIM                   1216
#define D_HCM_E_CPUFREQ_SET_PARAM           1220
#define D_HCM_E_SET_I2C_MON                 1217
#define D_HCM_E_PRCM_OPPX_USRMGN            1218
#define D_HCM_CTL_CLOSETOFULLTIME           1400
#define D_HCM_CTL_FULLTOCLOSETIME           1401
#define D_HCM_CTL_CLOSETOSTNDTIME           1402
#define D_HCM_CTL_STNDTOCLOSETIME           1403
#define D_HCM_CTL_STNDTOFULLTIME            1404
#define D_HCM_CTL_FULLTOSTNDTIME            1405
#define D_HCM_CTL_PAKITIME                  1406
#define D_HCM_E_VP_MMCHG_DISABLE3_CNT       2183
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP_LOG_S1 2184
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP_LOG_S2 2185
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP_LOG_S3 2186
#define D_HCM_E_VP_MMCHG_DISABLE3_TIMESTAMP 2187
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP1     2190
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP2     2191
#define D_HCM_E_VP_MMCHG_DISABLE3_TEMP3     2192
#define D_HCM_E_VP_MMCHG_DISABLE3_TIME1     2193
#define D_HCM_E_VP_MMCHG_DISABLE3_TIME2     2194
#define D_HCM_E_VP_MMCHG_DISABLE3_TIME3     2195
#define D_HCM_E_VP_MMCHG_ENABLE3_TEMP1      2196
#define D_HCM_E_VP_MMCHG_ENABLE3_TEMP2      2197
#define D_HCM_E_VP_MMCHG_ENABLE3_TEMP3      2198
#define D_HCM_E_VP_MMCHG_ENABLE3_TIME1      2199
#define D_HCM_E_VP_MMCHG_ENABLE3_TIME2      2200
#define D_HCM_E_VP_MMCHG_ENABLE3_TIME3      2201
#define D_HCM_E_VP_MMCHG_ENABLE3_OFFHOOK_TIME 2202
#define D_HCM_E_VP_CAM_DISABLE3_CNT         2203
#define D_HCM_E_VP_CAM_DISABLE3_TEMP_LOG_S1 2204
#define D_HCM_E_VP_CAM_DISABLE3_TEMP_LOG_S2 2205
#define D_HCM_E_VP_CAM_DISABLE3_TEMP_LOG_S3 2206
#define D_HCM_E_VP_CAM_DISABLE3_TEMP_LOG_S4 2207
#define D_HCM_E_VP_CAM_DISABLE3_TIMESTAMP   2208
#define D_HCM_E_VP_CAM_DISABLE_TEMP7        2209
#define D_HCM_E_VP_CAM_DISABLE_TEMP8        2210
#define D_HCM_E_VP_CAM_DISABLE_TEMP9        2211
#define D_HCM_E_VP_CAM_DISABLE_TEMP10       2212
#define D_HCM_E_VP_CAM_DISABLE_TIME7        2213
#define D_HCM_E_VP_CAM_DISABLE_TIME8        2214
#define D_HCM_E_VP_CAM_DISABLE_TIME9        2215
#define D_HCM_E_VP_CAM_DISABLE_TIME10       2216
#define D_HCM_E_VP_CAM_ENABLE_TEMP7         2217
#define D_HCM_E_VP_CAM_ENABLE_TEMP8         2218
#define D_HCM_E_VP_CAM_ENABLE_TEMP9         2219
#define D_HCM_E_VP_CAM_ENABLE_TEMP10        2220
#define D_HCM_E_VP_CAM_ENABLE_TIME7         2221
#define D_HCM_E_VP_CAM_ENABLE_TIME8         2222
#define D_HCM_E_VP_CAM_ENABLE_TIME9         2223
#define D_HCM_E_VP_CAM_ENABLE_TIME10        2224
#define D_HCM_E_LCD_DRV_BLC_B8BACDCE_MODE1  1442
#define D_HCM_E_LCD_DRV_BLC_B8BACDCE_MODE2  1443
#define D_HCM_E_LCD_DRV_BLC_B8BACDCE_MODE3  1444
#define D_HCM_E_LCD_DRV_BLC_B8BACDCE_MODE4  1445
#define D_HCM_E_MDP_DMAP_GC_COLOR0          1446
#define D_HCM_E_MDP_DMAP_GC_COLOR1          1447
#define D_HCM_E_MDP_DMAP_GC_COLOR2          1448
#define D_HCM_E_LCD_DRV_INIT_55             1500
#define D_HCM_E_LCD_DRV_BLC_B9_MODE1        1473
#define D_HCM_E_LCD_DRV_BLC_B9_MODE2        1472
#define D_HCM_E_LCD_DRV_BLC_B9_MODE3        1471
#define D_HCM_E_LCD_DRV_BLC_B9_MODE4        1470
#define D_HCM_E_LCD_DRV_BLC_B9_SELECT       1469
#define D_HCM_LCD_REFLESH_ON                1468
#define D_HCM_LCD_RETRANS_ON                1467
#define D_HCM_LCD_REFLESH_PERIOD            1466
#define D_HCM_E_LCD_BLC_STOP_NUM            1501
#define D_HCM_CAM_PLL_FSHIFT_OUT            1533
#define D_HCM_CAM_FSHIFT_TIMING_WAIT        1537
#define D_HCM_CAM_FSHIFT_FLG                1538
#define D_HCM_CAM_FSHIFT_TH_DTV_OUT         1539
#define D_HCM_CAM_FSHIFT_TH_FOMA_OUT        1540
#define D_HCM_CAM_FSHIFT_TH_DTV_IN          1541
#define D_HCM_CAM_FSHIFT_TH_FOMA_IN         1542
#define D_HCM_CAM_FSHIFT_D_OUT              1543
#define D_HCM_CAM_FSHIFT_D_IN               1544
#define D_HCM_E_CAM_FSHIFT_D_OUT2           1545
#define D_HCM_STATIC_ELE_RESET_MEASURES_FLG 1546
#define D_HCM_CAM_VCLK_DRIVE_CAPACITY       1547
#define D_HCM_CAM_WAIT_AFTER_STILL          1548
#define D_HCM_E_CAM_FRI_CYCLE               1549
#define D_HCM_E_CAM_FRI_FLCLESS             1550
#define D_HCM_E_CAM_FRI_FLCHZ               1551
#define D_HCM_E_CAM_FRI_HAN                 1552
#define D_HCM_LPWMON                        1570
#define D_HCM_LPWMON_ECO                    1571
#define D_HCM_LPWMON_HIGH                   1572
#define D_HCM_LPWMON_POWERMODE              1573
#define D_HCM_FULL_SCALE_CURRENT            1575
#define D_HCM_FULL_SCALE_CURRENT_ECO        1576
#define D_HCM_FULL_SCALE_CURRENT_HIGH       1577
#define D_HCM_RGBPWM                        1574
#define D_HCM_E_DTV_UNVOL_DAT               2169
#define D_HCM_E_DTV_ANTENNA_PICT            2170
#define D_HCM_E_DTV_CN_DAT                  2171
#define D_HCM_E_DTV_UNVOL_DAT2              2188
#define D_HCM_E_MM_UNVOL_DAT                2172
#define D_HCM_E_MM_ANTENNA_PICT             2173
#define D_HCM_E_MM_UNVOL_DAT2               2174
#define D_HCM_E_TUNER_UNVOL_DAT             2175
#define D_HCM_E_DTV_ANTENNA_SELECT          2181
#define D_HCM_OPTSEN_KEYBL_THRESHOLD        1587
#define D_HCM_OPTSEN_LCDBL_POLL             1588
#define D_HCM_E_OPTSEN_LUX_B                1578
#define D_HCM_E_OPTSEN_LUX_C                1579
#define D_HCM_E_OPTSEN_LUX_D                1580
#define D_HCM_E_OPTSEN_ATIME_14             1581
#define D_HCM_E_OPTSEN_ATIME_16             1582
#define D_HCM_OPTISEN_LUX_10                1505
#define D_HCM_OPTISEN_LUX_12                1589
#define D_HCM_OPTISEN_RANGE                 1732
#define D_HCM_E_OPTSEN_WAIT_TIME_10         1506
#define D_HCM_E_OPTSEN_WAIT_TIME_12         1733
#define D_HCM_E_OPTSEN_RISE_TIME            1590
#define D_HCM_E_CFG_OPTSEN_000              1591
#define D_HCM_E_CFG_OPTSEN_001              1592
#define D_HCM_E_CFG_OPTSEN_002              1593
#define D_HCM_E_OPTSEN_THRESH_LV1           1594
#define D_HCM_E_OPTSEN_THRESH_LV2           1595
#define D_HCM_E_OPTSEN_THRESH_LV3           1596
#define D_HCM_E_OPTSEN_THRESH_LV4           1597
#define D_HCM_E_OPTSEN_THRESH_LV5           1598
#define D_HCM_E_OPTSEN_THRESH_LV6           1599
#define D_HCM_E_OPTSEN_THRESH_LV7           1600
#define D_HCM_E_OPTSEN_THRESH_LV8           1601
#define D_HCM_E_OPTSEN_THRESH_LV9           1602
#define D_HCM_E_OPTSEN_HIST_LV1             1603
#define D_HCM_E_OPTSEN_HIST_LV2             1604
#define D_HCM_E_OPTSEN_HIST_LV3             1605
#define D_HCM_E_OPTSEN_HIST_LV4             1606
#define D_HCM_E_OPTSEN_HIST_LV5             1607
#define D_HCM_E_OPTSEN_HIST_LV6             1608
#define D_HCM_E_OPTSEN_HIST_LV7             1609
#define D_HCM_E_OPTSEN_HIST_LV8             1610
#define D_HCM_E_OPTSEN_HIST_LV9             1611
#define D_HCM_E_AS_DIRECTION                1616
#define D_HCM_E_HAP_RATED_VOL               1562
#define D_HCM_E_HAP_CLAMP_VOL               1563
#define D_HCM_E_HAP_LOSS_COMPENSATION       1564
#define D_HCM_E_HAP_BACK_EMF                1565
#define D_HCM_E_HAP_FEEDBACK_CNT            1566
#define D_HCM_E_HAP_CONTROL_1               1567
#define D_HCM_E_HAP_CONTROL_2               1568
#define D_HCM_E_HAP_CONTROL_3               1569
#define D_HCM_E_PROX_COMMAND1               1617
#define D_HCM_E_CFG_OPTSEN_003              1620
#define D_HCM_E_PROX_WAIT_TIME              1734
#define D_HCM_E_PROX_PTIME                  1618
#define D_HCM_E_TPL_OPE_MODE                1739
#define D_HCM_E_TPL_INT_EVENT               1740
#define D_HCM_E_TPL_X_DEAD_AREA_L           1650
#define D_HCM_E_TPL_Y_DEAD_AREA_L           1651
#define D_HCM_E_TPL_X_FILL_START_L          1652
#define D_HCM_E_TPL_Y_FILL_START_L          1653
#define D_HCM_E_TPL_MIN_X                   1749
#define D_HCM_E_TPL_MIN_Y                   1750
#define D_HCM_E_TPL_MAX_X                   1751
#define D_HCM_E_TPL_MAX_Y                   1752
#define D_HCM_E_TPL_POWERON_ERR_TS          1774
#define D_HCM_E_TPL_SUSPEND_ERR_TS          1775
#define D_HCM_E_TPL_DEVICE_ERR_TS           1776
#define D_HCM_E_TPL_HEALTHCHK_ERR_TS        1777
#define D_HCM_E_TPL_RECOVER_ERR_TS          1778
#define D_HCM_E_TPL_DEVINIT_ERR_TS          1779
#define D_HCM_E_TPL_FWWRITE_ERR_TS          1780
#define D_HCM_E_TPL_COMM_ERR_TS             1781
#define D_HCM_E_TPL_X_FIN_DELTA             1628
#define D_HCM_E_TPL_Y_FIN_DELTA             1629
#define D_HCM_E_TPL_X_PEN_DELTA             1630
#define D_HCM_E_TPL_Y_PEN_DELTA             1631
#define D_HCM_E_TPL_ENA_SMOOTH              1632
#define D_HCM_E_TPL_ENA_SMOOTH_THR          2143
#define D_HCM_E_TPL_PRIOR_TIME_FIN2PEN      1633
#define D_HCM_E_TPL_PEN_VEL_THR             1635
#define D_HCM_E_TPL_P_FIN_OFFSET            1636
#define D_HCM_E_TPL_L_FIN_OFFSET            1637
#define D_HCM_E_TPL_X_DEAD_AREA             1638
#define D_HCM_E_TPL_Y_DEAD_AREA             1639
#define D_HCM_E_TPL_X_FILL_START            1640
#define D_HCM_E_TPL_Y_FILL_START            1641
#define D_HCM_E_TPL_POWERON_ERR             2130
#define D_HCM_E_TPL_SUSPEND_ERR             2131
#define D_HCM_E_TPL_DEVICE_ERR              2132
#define D_HCM_E_TPL_HEALTHCHK_ERR           2134
#define D_HCM_E_TPL_RECOVER_ERR             2135
#define D_HCM_E_TPL_DEVINIT_ERR             2136
#define D_HCM_E_TPL_FWWRITE_ERR             2137
#define D_HCM_E_TPL_COMM_ERR                2138
#define D_HCM_E_TPL_ERR_INFO_DUMP_STS       2139
#define D_HCM_E_TPL_ERR_INFO_FW_CAUSE       2140
#define D_HCM_E_CALIB_PARAM_X0TC_PEN        1642
#define D_HCM_E_CALIB_PARAM_Y0TC_PEN        1662
#define D_HCM_E_CALIB_PARAM_0_SIN_PEN       1663
#define D_HCM_E_CALIB_PARAM_0_COS_PEN       1664
#define D_HCM_E_CALIB_PARAM_0_XMIN_PEN      1665
#define D_HCM_E_CALIB_PARAM_0_YMIN_PEN      1666
#define D_HCM_E_CALIB_PARAM_0_XMAX_PEN      1667
#define D_HCM_E_CALIB_PARAM_0_YMAX_PEN      1668
#define D_HCM_E_CALIB_PARAM_X90TC_PEN       1669
#define D_HCM_E_CALIB_PARAM_Y90TC_PEN       1670
#define D_HCM_E_CALIB_PARAM_90_SIN_PEN      1671
#define D_HCM_E_CALIB_PARAM_90_COS_PEN      1672
#define D_HCM_E_CALIB_PARAM_90_XMIN_PEN     1673
#define D_HCM_E_CALIB_PARAM_90_YMIN_PEN     1674
#define D_HCM_E_CALIB_PARAM_90_XMAX_PEN     1675
#define D_HCM_E_CALIB_PARAM_90_YMAX_PEN     1676
#define D_HCM_E_CALIB_PARAM_X180TC_PEN      1677
#define D_HCM_E_CALIB_PARAM_Y180TC_PEN      1678
#define D_HCM_E_CALIB_PARAM_180_SIN_PEN     1679
#define D_HCM_E_CALIB_PARAM_180_COS_PEN     1680
#define D_HCM_E_CALIB_PARAM_180_XMIN_PEN    1681
#define D_HCM_E_CALIB_PARAM_180_YMIN_PEN    1682
#define D_HCM_E_CALIB_PARAM_180_XMAX_PEN    1683
#define D_HCM_E_CALIB_PARAM_180_YMAX_PEN    1684
#define D_HCM_E_CALIB_PARAM_X270TC_PEN      1736
#define D_HCM_E_CALIB_PARAM_Y270TC_PEN      1737
#define D_HCM_E_CALIB_PARAM_270_SIN_PEN     1738
#define D_HCM_E_CALIB_PARAM_270_COS_PEN     1799
#define D_HCM_E_CALIB_PARAM_270_XMIN_PEN    1800
#define D_HCM_E_CALIB_PARAM_270_YMIN_PEN    1801
#define D_HCM_E_CALIB_PARAM_270_XMAX_PEN    1802
#define D_HCM_E_CALIB_PARAM_270_YMAX_PEN    1803
#define D_HCM_E_CALIB_PARAM_X0TC_FIN        1804
#define D_HCM_E_CALIB_PARAM_Y0TC_FIN        1805
#define D_HCM_E_CALIB_PARAM_0_SIN_FIN       1806
#define D_HCM_E_CALIB_PARAM_0_COS_FIN       1807
#define D_HCM_E_CALIB_PARAM_0_XMIN_FIN      1808
#define D_HCM_E_CALIB_PARAM_0_YMIN_FIN      1809
#define D_HCM_E_CALIB_PARAM_0_XMAX_FIN      1810
#define D_HCM_E_CALIB_PARAM_0_YMAX_FIN      1811
#define D_HCM_E_CALIB_PARAM_X90TC_FIN       1812
#define D_HCM_E_CALIB_PARAM_Y90TC_FIN       1813
#define D_HCM_E_CALIB_PARAM_90_SIN_FIN      1814
#define D_HCM_E_CALIB_PARAM_90_COS_FIN      1815
#define D_HCM_E_CALIB_PARAM_90_XMIN_FIN     1816
#define D_HCM_E_CALIB_PARAM_90_YMIN_FIN     1817
#define D_HCM_E_CALIB_PARAM_90_XMAX_FIN     1818
#define D_HCM_E_CALIB_PARAM_90_YMAX_FIN     1819
#define D_HCM_E_CALIB_PARAM_X180TC_FIN      1820
#define D_HCM_E_CALIB_PARAM_Y180TC_FIN      1821
#define D_HCM_E_CALIB_PARAM_180_SIN_FIN     1822
#define D_HCM_E_CALIB_PARAM_180_COS_FIN     1823
#define D_HCM_E_CALIB_PARAM_180_XMIN_FIN    1824
#define D_HCM_E_CALIB_PARAM_180_YMIN_FIN    1825
#define D_HCM_E_CALIB_PARAM_180_XMAX_FIN    1826
#define D_HCM_E_CALIB_PARAM_180_YMAX_FIN    1827
#define D_HCM_E_CALIB_PARAM_X270TC_FIN      1828
#define D_HCM_E_CALIB_PARAM_Y270TC_FIN      1829
#define D_HCM_E_CALIB_PARAM_270_SIN_FIN     1830
#define D_HCM_E_CALIB_PARAM_270_COS_FIN     1831
#define D_HCM_E_CALIB_PARAM_270_XMIN_FIN    1832
#define D_HCM_E_CALIB_PARAM_270_YMIN_FIN    1833
#define D_HCM_E_CALIB_PARAM_270_XMAX_FIN    1834
#define D_HCM_E_CALIB_PARAM_270_YMAX_FIN    1835
#define D_HCM_E_CALIB_TC_XMAX_PEN           1836
#define D_HCM_E_CALIB_TC_YMAX_PEN           1837
#define D_HCM_E_CALIB_TC_XMAX_FIN           1838
#define D_HCM_E_CALIB_TC_YMAX_FIN           1839
#define D_HCM_E_CALIB_TD_XMAX_PEN           1840
#define D_HCM_E_CALIB_TD_YMAX_PEN           1841
#define D_HCM_E_CALIB_TD_XMAX_FIN           1842
#define D_HCM_E_CALIB_TD_YMAX_FIN           1843
#define D_HCM_E_CALIB_P_CALIBED_Z           1646
#define D_HCM_E_CALIB_L_CALIBED_Z           1647
#define D_HCM_E_CALIB_ASM_GAP_X             1648
#define D_HCM_E_CALIB_ASM_GAP_Y             1649
#define D_HCM_E_MAG_MOUNTOPTION             1696
#define D_HCM_E_MAG_LOG                     1697
#define D_HCM_E_MAG_X_OFFSET_0              1698
#define D_HCM_E_MAG_Y_OFFSET_0              1699
#define D_HCM_E_MAG_Z_OFFSET_0              1700
#define D_HCM_E_MAG_X_OFFSET_1              1701
#define D_HCM_E_MAG_Y_OFFSET_1              1702
#define D_HCM_E_MAG_Z_OFFSET_1              1703
#define D_HCM_E_MAG_X_OFFSET_2              1704
#define D_HCM_E_MAG_Y_OFFSET_2              1705
#define D_HCM_E_MAG_Z_OFFSET_2              1706
#define D_HCM_E_MAG_X_OFFSET_3              1707
#define D_HCM_E_MAG_Y_OFFSET_3              1708
#define D_HCM_E_MAG_Z_OFFSET_3              1709
#define D_HCM_E_MAG_X_OFFSET_4              1710
#define D_HCM_E_MAG_Y_OFFSET_4              1711
#define D_HCM_E_MAG_Z_OFFSET_4              1712
#define D_HCM_E_MAG_X_OFFSET_5              2144
#define D_HCM_E_MAG_Y_OFFSET_5              2145
#define D_HCM_E_MAG_Z_OFFSET_5              2146
#define D_HCM_E_MAG_X_OFFSET_6              2147
#define D_HCM_E_MAG_Y_OFFSET_6              2148
#define D_HCM_E_MAG_Z_OFFSET_6              2149
#define D_HCM_E_MAG_X_OFFSET_7              2150
#define D_HCM_E_MAG_Y_OFFSET_7              2151
#define D_HCM_E_MAG_Z_OFFSET_7              2152
#define D_HCM_E_MAG_X_OFFSET_8              2153
#define D_HCM_E_MAG_Y_OFFSET_8              2154
#define D_HCM_E_MAG_Z_OFFSET_8              2155
#define D_HCM_E_MAG_X_OFFSET_9              2156
#define D_HCM_E_MAG_Y_OFFSET_9              2157
#define D_HCM_E_MAG_Z_OFFSET_9              2158
#define D_HCM_E_MAG_CURRENT_THRESH_0        2159
#define D_HCM_E_MAG_CURRENT_THRESH_1        2160
#define D_HCM_E_MAG_CURRENT_THRESH_2        2161
#define D_HCM_E_MAG_CURRENT_THRESH_3        2162
#define D_HCM_E_MAG_CURRENT_THRESH_4        2163
#define D_HCM_E_MAG_CURRENT_THRESH_5        2164
#define D_HCM_E_MAG_CURRENT_THRESH_6        2165
#define D_HCM_E_MAG_CURRENT_THRESH_7        2166
#define D_HCM_E_MAG_CURRENT_THRESH_8        2167
#define D_HCM_E_TCHSEN_SLEEP_MODE           1900
#define D_HCM_E_TCHSEN_SLEEP_INTVL_RUNNING  1901
#define D_HCM_E_TCHSEN_SLEEP_INTVL_IDLE     1902
#define D_HCM_E_TCHSEN_ACTIVE_INTVL         1903
#define D_HCM_E_TCHSEN_INT_MASK_RUNNING     1904
#define D_HCM_E_TCHSEN_INT_MASK_IDLE        1905
#define D_HCM_E_TCHSEN_SLEEP_SCAN_MASK      1906
#define D_HCM_E_TCHSEN_AUTO_RESET_CTRL      1907
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_0      1908
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_1      1909
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_2      1910
#define D_HCM_E_TCHSEN_DEBOUNCE             1911
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_0    1912
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_1    1913
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_2    1914
#define D_HCM_E_TCHSEN_NGTV_NOISE_THRESHOLD_0 1915
#define D_HCM_E_TCHSEN_NGTV_NOISE_THRESHOLD_1 1916
#define D_HCM_E_TCHSEN_NGTV_NOISE_THRESHOLD_2 1917
#define D_HCM_E_TCHSEN_BSLN_UPDT_THRESHOLD_0 1918
#define D_HCM_E_TCHSEN_BSLN_UPDT_THRESHOLD_1 1919
#define D_HCM_E_TCHSEN_BSLN_UPDT_THRESHOLD_2 1920
#define D_HCM_E_TCHSEN_LOW_BSLN_RESET_0     1921
#define D_HCM_E_TCHSEN_LOW_BSLN_RESET_1     1922
#define D_HCM_E_TCHSEN_LOW_BSLN_RESET_2     1923
#define D_HCM_E_TCHSEN_RESOLUTION           1924
#define D_HCM_E_TCHSEN_SCAN_SPEED           1925
#define D_HCM_E_TCHSEN_PRESCALER            1926
#define D_HCM_E_TCHSEN_RESOLUTION_IDLE      1929
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_0_IDLE 1930
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_1_IDLE 1931
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_2_IDLE 1932
#define D_HCM_E_TCHSEN_DEBOUNCE_IDLE        1933
#define D_HCM_E_TCHSEN_HEALTHCHK_ERR        1927
#define D_HCM_E_TCHSEN_COMM_ERR             1928
#define D_HCM_E_TCHSEN_SLEEP_WAIT_TIME      1934
#define D_HCM_E_TCHSEN_RESET_WAIT_TIME      1935
#define D_HCM_E_TCHSEN_SCAN_WAIT_TIME       1936
#define D_HCM_E_TCHSEN_WAKEUP_CTRL          1937
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_0_OFFSET 1938
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_1_OFFSET 1939
#define D_HCM_E_TCHSEN_FNG_THRESHOLD_2_OFFSET 1940
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_0_IDLE 2509
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_1_IDLE 2510
#define D_HCM_E_TCHSEN_NOISE_THRESHOLD_2_IDLE 2511
#define D_HCM_E_GYRO_MOUNTOPTION            1950
#define D_HCM_AGING_PROC_FLG                2000
#define D_HCM_AGING_INIT_FLG                2001
#define D_HCM_MANU_PROC_FLG                 2002
#define D_HCM_DAT_CHECK_N                   2003
#define D_HCM_FG_OCV_FLAG                   2006
#define D_HCM_OPTSEN_REV                    2007
#define D_HCM_E_PROX_PPULSE                 2008
#define D_HCM_E_PROX_CONTROL                2009
#define D_HCM_E_PROX_POFFSET                2010
#define D_HCM_E_AS_MOTION_THRESH            2012
#define D_HCM_TIME_ADJUST                   2700
#define D_HCM_MANU_SERIAL_NO                2013
#define D_HCM_E_PROX_COMMAND2               2025
#define D_HCM_E_TESTSOFT_EN_FLG             2701
#define D_HCM_E_PROX_INT_LT                 2014
#define D_HCM_E_PROX_INT_HT                 2015
#define D_HCM_OMF_UART                      2016
#define D_HCM_OMF_COM_PARA                  2017
#define D_HCM_MAX_VOLTAGE_ADJUST            2702
#define D_HCM_COOL_TEMP_ADJUST              2703
#define D_HCM_WARM_TEMP_ADJUST              2704
#define D_HCM_E_FW_H                        2027
#define D_HCM_E_FW_L                        2028
#define D_HCM_E_GRADE                       2029
#define D_HCM_WIRELESSCHARGE_MODEL_CODE     2031
#define D_HCM_WIRELESSCHARGE_FW_VERSION     2168
#define D_HCM_AD_PCB_VERSION                2030
#define D_HCM_WLAN_P2G_TABLE                2018
#define D_HCM_WLAN_PPA_STEPS                2019
#define D_HCM_WLAN_PD_CURVES                2020
#define D_HCM_E_VP_OFFSET1                  2021
#define D_HCM_E_VP_OFFSET2                  2022
#define D_HCM_E_VP_OFFSET3                  2023
#define D_HCM_E_VP_OFFSET4                  2024
#define D_HCM_HKADC_ADJUST1                 2705
#define D_HCM_HKADC_ADJUST2                 2706
#define D_HCM_E_AS_FLAG_SENSOE_NVM00        2225
#define D_HCM_E_AS_FLAG_SENSOE_NVM01        2226
#define D_HCM_E_AS_FLAG_SENSOE_NVM02        2227
#define D_HCM_E_AS_FLAG_SENSOE_NVM03        2228
#define D_HCM_E_AS_FLAG_SENSOE_NVM04        2229
#define D_HCM_E_AS_FLAG_SENSOE_NVM05        2230
#define D_HCM_E_AS_FLAG_SENSOE_NVM06        2231
#define D_HCM_E_AS_FLAG_SENSOE_NVM07        2232
#define D_HCM_E_AS_FLAG_SENSOE_NVM08        2233
#define D_HCM_E_AS_FLAG_SENSOE_NVM09        2234
#define D_HCM_E_AS_FLAG_SENSOE_NVM0A        2235
#define D_HCM_E_AS_FLAG_SENSOE_NVM0B        2236
#define D_HCM_E_AS_FLAG_SENSOE_NVM0C        2237
#define D_HCM_E_AS_FLAG_SENSOE_NVM0D        2238
#define D_HCM_E_AS_FLAG_SENSOE_NVM0E        2239
#define D_HCM_E_AS_FLAG_SENSOE_NVM0F        2240
#define D_HCM_E_AS_FLAG_SENSOE_NVM10        2241
#define D_HCM_E_AS_FLAG_SENSOE_NVM11        2242
#define D_HCM_E_AS_FLAG_SENSOE_NVM12        2243
#define D_HCM_E_AS_FLAG_SENSOE_NVM13        2244
#define D_HCM_E_AS_FLAG_SENSOE_NVM14        2245
#define D_HCM_E_AS_FLAG_SENSOE_NVM15        2246
#define D_HCM_E_AS_FLAG_SENSOE_NVM16        2247
#define D_HCM_E_AS_FLAG_SENSOE_NVM17        2248
#define D_HCM_E_AS_FLAG_SENSOE_NVM18        2249
#define D_HCM_E_AS_FLAG_SENSOE_NVM19        2250
#define D_HCM_E_AS_FLAG_SENSOE_NVM1A        2251
#define D_HCM_E_AS_FLAG_SENSOE_BACKUP       2252
#define D_HCM_E_AS_FLAG_SENSOE_CAL_X        2253
#define D_HCM_E_AS_FLAG_SENSOE_CAL_Y        2254
#define D_HCM_E_AS_FLAG_SENSOE_CAL_Z        2255
#define D_HCM_WLAN_PER_CHANNEL_POWER_GAIN_OFFSET 2046
#define D_HCM_WLAN_EFUSE                    2047
#define D_HCM_SIGREC                        2033
#define D_HCM_E_ROOT_JUDGMENT_FLG           2115
#define D_HCM_E_ROOT_JUDGMENT_CNT           2116
#define D_HCM_E_ROOT_JUDGMENT_FIRST_TIME    2117
#define D_HCM_E_ROOT_JUDGMENT_CURRENT_TIME  2118
#define D_HCM_AGING_STATE_FLG               2034
#define D_HCM_E_FASTBOOT_ONOFF_FLG          2119
#define D_HCM_E_BOOT_KERNEL_FLG             2112
#define D_HCM_E_DIAG_ONOFF_FLG              2113
#define D_HCM_E_FORMATMODE_ONOFF_FLG        2114
#define D_HCM_DAT_KYOUTAI                      1
#define D_HCM_FWUPDATE                      2036
#define D_HCM_CUSTOMIZE_ID                  2120
#define D_HCM_CUSTOMIZE_STATUS              2121
#define D_HCM_RAM_DUMP_ADDRESS              2037
#define D_HCM_LKCD_DUMP_ADDRESS             2038
#define D_HCM_DAT_CHECK_E                   2039
#define D_HCM_E_MODEL_AGE                      0
#define D_HCM_E_WRITE_COMP_NUM                 5
#define D_HCM_E_FOTA_SUBSTS                    3
#define D_HCM_E_FOTA_STS                       2
#define D_HCM_ALARM_NAND_INIT_INVBLK_CNT    2041
#define D_HCM_ALARM_NAND_TOTAL_INVBLK_CNT   2042
#define D_HCM_ALARM_NAND_BOOT1_INIT_INVBLK_CNT 2044
#define D_HCM_ALARM_NAND_BOOT2_INIT_INVBLK_CNT 2045
#define D_HCM_ALARM_NAND_INIT_INVBLK_CNT2   2048
#define D_HCM_ALARM_NAND_TOTAL_INVBLK_CNT2  2049
#define D_HCM_E_ALARM_NAND_READ_ECC         2043
#define D_HCM_E_NAND_ANALYZE_1              2066
#define D_HCM_E_NAND_ANALYZE_2              2067
#define D_HCM_DAT_CHECK_C                   2040
#define D_HCM_E_ALARM_NAND_BADMARK1         2068
#define D_HCM_E_ALARM_NAND_BADMARK2         2069
#define D_HCM_E_ALARM_NAND_BADMARK3         2070
#define D_HCM_E_ALARM_NAND_BADMARK4         2071
#define D_HCM_E_ALARM_NAND_BADMARK5         2072
#define D_HCM_E_ALARM_NAND_BADMARK6         2073
#define D_HCM_E_ALARM_NAND_BADMARK7         2074
#define D_HCM_E_ALARM_NAND_BADMARK8         2075
#define D_HCM_E_ALARM_NAND_BADMARK9         2076
#define D_HCM_E_ALARM_NAND_BADMARK10        2077
#define D_HCM_E_ALARM_NAND_BADMARK11        2078
#define D_HCM_E_ALARM_NAND_BADMARK12        2079
#define D_HCM_E_ALARM_NAND_BADMARK13        2080
#define D_HCM_E_ALARM_NAND_BADMARK14        2081
#define D_HCM_E_ALARM_NAND_BADMARK15        2082
#define D_HCM_E_ALARM_NAND_BADMARK16        2083
#define D_HCM_E_ALARM_NAND_BADMARK17        2084
#define D_HCM_E_ALARM_NAND_BADMARK18        2085
#define D_HCM_E_ALARM_NAND_BADMARK19        2086
#define D_HCM_E_ALARM_NAND_BADMARK20        2087
#define D_HCM_E_ALARM_NAND_BADMARK21        2088
#define D_HCM_E_ALARM_NAND_BADMARK22        2089
#define D_HCM_E_ALARM_NAND_BADMARK23        2090
#define D_HCM_E_ALARM_NAND_BADMARK24        2091
#define D_HCM_E_ALARM_NAND_BADMARK25        2092
#define D_HCM_E_ALARM_NAND_BADMARK26        2093
#define D_HCM_E_ALARM_NAND_BADMARK27        2094
#define D_HCM_E_ALARM_NAND_BADMARK28        2095
#define D_HCM_E_ALARM_NAND_BADMARK29        2096
#define D_HCM_E_ALARM_NAND_BADMARK30        2097
#define D_HCM_E_ALARM_NAND_BADMARK31        2098
#define D_HCM_E_ALARM_NAND_BADMARK32        2099
#define D_HCM_E_ALARM_NAND_BADMARK33        2100
#define D_HCM_E_ALARM_NAND_BADMARK34        2101
#define D_HCM_E_ALARM_NAND_BADMARK35        2102
#define D_HCM_E_ALARM_NAND_BADMARK36        2103
#define D_HCM_E_ALARM_NAND_BADMARK37        2104
#define D_HCM_E_ALARM_NAND_BADMARK38        2105
#define D_HCM_E_ALARM_NAND_BADMARK39        2106
#define D_HCM_E_ALARM_NAND_BADMARK40        2107
#define D_HCM_E_ALARM_NAND_BADMARK41        2108
#define D_HCM_E_ALARM_NAND_BADMARK42        2109
#define D_HCM_E_ALARM_NAND_BADMARK43        2110
#define D_HCM_E_ALARM_NAND_BADMARK44        2111
#define D_HCM_E_DEINITIALIZE_SPARE00        2050
#define D_HCM_E_DEINITIALIZE_SPARE01        2051
#define D_HCM_E_DEINITIALIZE_SPARE02        2052
#define D_HCM_E_DEINITIALIZE_SPARE03        2053
#define D_HCM_E_DEINITIALIZE_SPARE04        2054
#define D_HCM_E_DEINITIALIZE_SPARE05        2055
#define D_HCM_E_DEINITIALIZE_SPARE06        2056
#define D_HCM_E_DEINITIALIZE_SPARE07        2057
#define D_HCM_E_DEINITIALIZE_SPARE08        2058
#define D_HCM_E_DEINITIALIZE_SPARE09        2059
#define D_HCM_E_DEINITIALIZE_SPARE10        2060
#define D_HCM_E_DEINITIALIZE_SPARE11        2061
#define D_HCM_E_DEINITIALIZE_SPARE12        2062
#define D_HCM_E_DEINITIALIZE_SPARE13        2063
#define D_HCM_E_DEINITIALIZE_SPARE14        2064
#define D_HCM_E_DEINITIALIZE_SPARE15        2065
#define D_HCM_DATE_YMD                      2500
#define D_HCM_TECA_AUTH                     2501
#define D_HCM_E_P2P_MACADDRESS              2499
#define D_HCM_BT_ADD                        2502
#define D_HCM_E_WLAN_MACADDRESS             2503
#define D_HCM_MODEL_NAME                    2504
#define D_HCM_E_SD_DEVICE_KEY_ID            2505
#define D_HCM_E_DTCP_DEVICE_KEY_ID          2506
#define D_HCM_E_WIDEVINE_SERIAL_NO          2189
#define D_HCM_E_HDCP_SERIAL_NO              2498
#define D_HCM_DAT_CHECK_M                   2999
/* end of EEPROM map define */

#endif                                           /* __hcm_eep_h__             */
