#ifndef _SCHED_HISTORY_H
#define _SCHED_HISTORY_H

#ifdef CONFIG_SCHED_HISTORY

#define D_SCHED_PROCNAME_MAX  1024
#define E_SCHED_HISTORY_ID_NUM  20

/*
 * E_SCHED_HISTORY_ID
 * MAX = D_SCHED_RESERVED_NUM
 */
enum E_SCHED_HISTORY_ID{
	E_SCHED_HISTORY_ID_ST = D_SCHED_PROCNAME_MAX
	, E_SCHED_HISTORY_WORKQUEUE_ST
	, E_SCHED_HISTORY_WORKQUEUE_ED
	, E_SCHED_HISTORY_TOP_HALF_HANDLER_ST
	, E_SCHED_HISTORY_TOP_HALF_HANDLER_ED
	, E_SCHED_HISTORY_SOFTIRQ_HACTION_ST
	, E_SCHED_HISTORY_SOFTIRQ_HACTION_ED
	, E_SCHED_HISTORY_SOFTIRQ_TASKLET_ST
	, E_SCHED_HISTORY_SOFTIRQ_TASKLET_ED
	, E_SCHED_HISTORY_SOFTIRQ_TASKLET_HACTION_ST
	, E_SCHED_HISTORY_SOFTIRQ_TASKLET_HACTION_ED
	, E_SCHED_HISTORY_ID_ED
};

void add_sched_history(unsigned short, unsigned int, void*);

extern unsigned char gCPU_RATE[CONFIG_NR_CPUS];

#endif /* CONFIG_SCHED_HISTORY */

#endif /* _SCHED_HISTORY_H */
