#####                          ST #####
EXTRA_CFLAGS :=

## PROC    
#EXTRA_CFLAGS += -DFELICA_DEBUG_PROC_ON

##                           
EXTRA_CFLAGS += -DFELIACA_SYS_LOG_ON
#EXTRA_CFLAGS += -DFELIACA_RAM_LOG_ON

##                ST
### FELICA_DEBUG_ALL
#FELICA_DEBUG_ALL := TRUE
FELICA_DEBUG_ALL := FALSE

### FELICA_DEBUG_ERR
FELICA_DEBUG_ERR := TRUE
#FELICA_DEBUG_ERR := FALSE

### FELICA_DEBUG_IF
#FELICA_DEBUG_IF  := TRUE
FELICA_DEBUG_IF  := FALSE
##                ED

# FELICA_DEBUG_IF
ifeq ($(FELICA_DEBUG_IF),TRUE)
EXTRA_CFLAGS += -DFELIACA_LOG_IF_STED
EXTRA_CFLAGS += -DFELIACA_LOG_IF_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_STED
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_STED
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_EXIF_STED
EXTRA_CFLAGS += -DFELIACA_LOG_EXIF_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_IF
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_DEV
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_ITR
endif

# FELICA_DEBUG_ERR
ifeq ($(FELICA_DEBUG_ERR),TRUE)
EXTRA_CFLAGS += -DFELIACA_LOG_IF_ASSERT
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_ASSERT
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_ASSERT
endif

# FELICA_DEBUG_ALL
ifeq ($(FELICA_DEBUG_ALL),TRUE)
EXTRA_CFLAGS += -DFELIACA_LOG_IF_STED
EXTRA_CFLAGS += -DFELIACA_LOG_IF_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_IF_ASSERT
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_STED
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_PRIV_ASSERT
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_STED
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_ITR_ASSERT
EXTRA_CFLAGS += -DFELIACA_LOG_EXIF_STED
EXTRA_CFLAGS += -DFELIACA_LOG_EXIF_PARAM
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_IF
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_DEV
EXTRA_CFLAGS += -DFELIACA_LOG_TERMINAL_ITR
endif
